name: Verify
on: [push]

jobs:
  # linters:
  #   name: Linters
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #     - name: Ruby gem cache
  #       uses: actions/cache@v2
  #       with:
  #         path: vendor/bundle
  #         key: ${{ runner.os }}-gems-v1-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-v1-
  #     - name: Install gems
  #       run: |
  #         bundle config path vendor/bundle
  #         bundle install --jobs 4 --retry 3
  #
  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.13.0
  #     - name: Find yarn cache location
  #       id: yarn-cache
  #       run: echo "::set-output name=dir::$(yarn cache dir)"
  #     - name: JS package cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ${{ steps.yarn-cache.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-
  #     - name: Install packages
  #       run: |
  #         yarn install --pure-lockfile
  #
  #     - name: Run linters
  #       run: |
  #         bin/rubocop --parallel
  #         bin/erblint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: mysql2://root:root@127.0.0.1/app?pool=30&encoding=utf8mb4&collation=utf8mb4_unicode_ci
    services:
      manticore:
        image: manticoresearch/manticore
        ports:
          - 9306:9306
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Mysql
        run: sudo systemctl start mysql.service
      # - name: Install manticore search
      #   run: |
      #     wget -qO - https://repo.manticoresearch.com/GPG-KEY-manticore | sudo apt-key add -
      #     wget https://repo.manticoresearch.com/manticore-repo.noarch.deb
      #     sudo dpkg -i manticore-repo.noarch.deb
      #     sudo apt update
      #     sudo apt install manticore manticore-columnar-lib

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-v1-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-v1
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        run: |
          bin/rails db:create db:schema:load

      - name: Run tests
        run: bin/rails test:system
